### ISSUE TITLE
Beta 11 can’t build on Netlify

### ISSUE THREAD

**Issue by johnridesabike** [shakacode/re-formality#97] opened 2021-02-21 18:45 UTC
I upgraded to Beta 11 (and upgraded `reason-react` to `@rescript/react`) and the build now fails when deploying to Netlify.

A variation of this error appears for every file in my project:

```
bsb: [5/11] assets/Contact_Form.iast
1:32:55 PM: FAILED: assets/Contact_Form.iast
1:32:55 PM: /opt/build/repo/node_modules/re-formality/ppx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/build/repo/node_modules/re-formality/ppx)

  We've found a bug for you!
  /opt/build/repo/assets/Contact_Form.resi
  
  Error while running external preprocessor
Command line: /opt/build/repo/node_modules/re-formality/ppx '/tmp/ppxd38401Contact_Form.resi' '/tmp/ppxd2563aContact_Form.resi’
```

Reverting to Beta 10 fixes the errors.

I can’t reproduce this on my local MacOS machine. I also tried some basic debugging (clearing Netlify cache, removing `node_modules`) but it didn’t make a difference.

**Comment by alexfedoseev** [comment] 2021-02-23 06:04
I suspect it’s either changes in GH Actions env, or esy, or both. I’m not sure I will be able to look into this until the next month, unfortunately.

**Comment by vasco3** [comment] 2021-02-25 20:20
I'm also having this issue in GH Actions and in Vercel.com

**Comment by alexfedoseev** [comment] 2021-02-26 08:27
There's a solution [on Discord](https://discord.com/channels/235176658175262720/235200837608144898) but I will be able to poke on it only next week. If anyone willing to submit a PR earlier, it will be totally welcomed :)

**Comment by alexfedoseev** [comment] 2021-03-08 13:06
I made some progress in #99 but it still fails with odd error. I'll comeback to it some time this week.

**Comment by alexfedoseev** [comment] 2021-03-09 11:30
@johnridesabike @vasco3 Would you mind trying out `4.0.0-beta.12`?

**Comment by johnridesabike** [comment] 2021-03-09 13:02
It still seems broken, although the error is different now

```
7:59:25 AM: bsb: [2/11] assets/Contact_Form.iast
7:59:25 AM: FAILED: assets/Contact_Form.iast
7:59:25 AM: sh: 1: /opt/build/repo/node_modules/re-formality/ppx: not found
7:59:25 AM:   We've found a bug for you!
  /opt/build/repo/assets/Contact_Form.resi
7:59:25 AM:   Error while running external preprocessor
7:59:25 AM: Command line: /opt/build/repo/node_modules/re-formality/ppx '/tmp/ppxc94e87Contact_Form.resi' '/tmp/ppx4888aeContact_Form.resi’
```

Deploying to Netlify. That error appears for every file in my project.

**Comment by alexfedoseev** [comment] 2021-03-09 13:32
@johnridesabike This is really weird. Do you know what linux setup they use? I'd spin up local Docker container to reproduce it locally.

Also, can you make sure that post-install scripts are not disabled on Netlify?

**Comment by johnridesabike** [comment] 2021-03-09 13:41
It looks like their build image is here: https://github.com/netlify/build-image
I’m using Ubuntu Xenial 16.04 (default).

AFAIK post-install scripts should work fine, since I believe some other packages I use depend on those. I’ll double-check though.

**Comment by alexfedoseev** [comment] 2021-03-09 14:08
Thanks! I will try it out tomorrow 👍

**Comment by gaku-sei** [comment] 2021-03-10 08:22
Just so you know this happens on Circle Ci as well using this Docker image: https://hub.docker.com/r/circleci/node

The error is the same as above: `sh: 1: /home/circleci/project/node_modules/re-formality/ppx: not found`. What's really weird is that the file actually exists 😕 

Here is the output of
```
ls -lah /home/circleci/project/node_modules/re-formality
/home/circleci/project/node_modules/re-formality/ppx
```

```
total 43M
....
-rwxr-xr-x   1 circleci circleci  22M Mar 10 08:19 ppx
.....
/bin/bash: line 1: /home/circleci/project/node_modules/re-formality/ppx: No such file or directory
```

So the file exists but when called `sh` complains it can't be found.

**Comment by alexfedoseev** [comment] 2021-03-10 12:03
I did some googling and apparently it means the binary still misses a dependency. I was able to reproduce it locally in a  docker container but have no clue what's wrong with the way linux binary is built. I'm not very familiar with the Reason's native side of things and Dune though, so I might miss something obvious.

**Comment by thehabbos007** [comment] 2021-04-25 14:42
Just weighing in as I had the same problem locally in WSL2
```
$ ldd ./node_modules/re-formality/ppx
        linux-vdso.so.1 (0x00007ffcb4fdf000)
        libc.musl-x86_64.so.1 => not found
```
I was missing musl libc, so I tried installing with `apt` which still didn't work as it was an older version (1.1.19-1). It spewed errors about `secure_getenv: symbol not found`.

I then tried compiling http://musl.libc.org/ from source at 1.2.2 and made sure it was symlinked with `sudo ln -s /usr/local/musl/lib/libc.so /lib/libc.musl-x86_64.so.1` and then the ppx executable worked!
```
$ ldd ./node_modules/re-formality/ppx
        linux-vdso.so.1 (0x00007ffd5e396000)
        libc.musl-x86_64.so.1 => /lib/libc.musl-x86_64.so.1 (0x00007fb0b4a38000)
```

I suspect the same issues happens in netlify, where perhaps only gnu libc is present, so it has trouble linking with musl libc :)

**Comment by alexfedoseev** [comment] 2021-05-23 09:30
@thehabbos007 Thanks for the info! Quick question: is there anything I can do on the build side to make it work w/o a need in user linking?

**Comment by thehabbos007** [comment] 2021-05-23 10:16
> 
> 
> @thehabbos007 Thanks for the info! Quick question: is there anything I can do on the build side to make it work w/o a need in user linking?

I can imagine statically building the ppx executable might be possible to make it work for all on linux?
Only problem would be increased binary size.

Changing the compiler to use glibc somehow for the ppx would also be a possibility, but it might break other usages (for alpine docker containers perhaps?)
I am not that familiar with esy/dune and the compiler, though so I can't give you any anecdotal fixes im afraid :)

**Comment by alexfedoseev** [comment] 2021-05-23 10:26
Gotcha, thanks for the input! Yeah, I tried to [build it statically](https://github.com/shakacode/re-formality/pull/99/files#diff-897b6bac6ef4d0c1b0a344e605423b96942a3d88e868794374778ed49d792c56R3), still couldn't make it work. But, as I mentioned, I'm too not very familiar with the Reason's native side of things and Dune, so I might miss something obvious.

**Comment by thehabbos007** [comment] 2021-05-23 10:29
I did find this, though, https://github.com/reasonml-community/graphql-ppx/compare/v0.4.6...v0.4.9 which might be helpful!

**Comment by alexfedoseev** [comment] 2021-05-27 09:52
@thehabbos007 Thanks for the link! I actually looked into this and did a similar custom dockerfile but it didn't work unfortunately.

**Comment by alexfedoseev** [comment] 2021-06-30 19:57
Hey folks, I think I finally fixed the linux build. Please try `4.0.0-beta.15`.

**Comment by JasoonS** [comment] 2021-07-03 18:11
@alexfedoseev Can confirm it is working for me. Thank you so much :pray:

**Comment by johnridesabike** [comment] 2021-07-05 13:21
I just upgraded a Netlify project to use beta 15 and it works!

**Comment by alexfedoseev** [comment] 2021-07-05 17:09
It was a stupid mistake that wasn't related to a static linking itself. Worth me a couple of days to solve. On CI, build step used static linking command was followed by the `esy x ...` test step, which overwrites the binary built with static linking. So this non-static binary was shipped.

**Comment by alexfedoseev** [comment] 2021-07-06 12:13
Fixed in #104.

**Closed by alexfedoseev** 2021-07-06 12:13 UTC

**Comment by Prateek13727** [comment] 2022-01-19 13:36
Hey Folks,

Building my project with `rescript` and `re-formality` for the first time in docker and the ppx is failing. This works fine in my local.

Has anyone faced this issue before Or let me know, I am mssing something?  I have limited experience with Docker. 

Cheers
Prateek

The Error Image
![image](https://user-images.githubusercontent.com/18599528/150138799-13054fed-52c4-47a1-a35f-b70cd07645af.png)

my Docker file

`FROM node:14.17.0-alpine

RUN apk add --no-cache git python3 g++ make musl-dev
RUN ln -s /usr/bin/python3 /usr/bin/python

# To make re-formality ppx work
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.30-r0/glibc-2.30-r0.apk
RUN apk add glibc-2.30-r0.apk

ENV LD_LIBRARY_PATH=/usr/lib:/lib64:/lib
ARG ENV
# Copy package.json, so that yarn install will only do a fresh installation of
# node modules if package.json is modified
ADD package.json .
ADD yarn.lock .
ARG GITHUB_READ_TOKEN
RUN echo -e "machine github.com\nlogin Prateek13727\npassword $GITHUB_READ_TOKEN" > ~/.netrc 
RUN yarn install --ignore-engines --frozen-lockfile
RUN rm ~/.netrc
ADD . ./
RUN yarn bs:build 
RUN yarn build:$ENV
# Expose the app port
EXPOSE 3003
COPY deploy/scripts/* /usr/bin/
ENTRYPOINT ["bash", "/usr/bin/run.sh"]
`

**Comment by Prateek13727** [comment] 2022-01-19 14:27
This is fixed. The issue was, I was using `RUN ADD . ./ `command in Dockerfile after `RUN yarn install --ignore-engines --frozen-lockfile `. Hence the `/node_modules` from my local were overriding the `node_modules` in my docker container. 

Also, `.dockerignore` will help
